apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: policy-set-security
spec:
  description: "Políticas de Segurança e Hardening"
  policies:
    - policy-security-privileged-denial
