apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-security-privileged-denial
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    # ── Regra 1: nenhum container com privileged: true ────────────────────
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-deny-privileged-containers
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            include: ["*"]
            exclude: ["kube-system", "open-cluster-management*", "haproxy-controller"]
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: v1
                kind: Pod
                spec:
                  containers:
                    - securityContext:
                        privileged: true
    # ── Regra 2: mesmo controle para initContainers ───────────────────────
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-deny-privileged-init-containers
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            include: ["*"]
            exclude: ["kube-system", "open-cluster-management*", "haproxy-controller"]
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: v1
                kind: Pod
                spec:
                  initContainers:
                    - securityContext:
                        privileged: true
    # ── Regra 3: Namespace label PSS não pode ser privileged ─────────────
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-deny-privileged-pss-label
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            include: ["*"]
            exclude: ["kube-system", "open-cluster-management*", "haproxy-controller"]
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  labels:
                    pod-security.kubernetes.io/enforce: privileged
