apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-capacity-default-limits
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-capacity-default-limits
        spec:
          remediationAction: enforce
          severity: medium
          namespaceSelector:
            include: ["default", "*-workloads"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: LimitRange
                metadata:
                  name: workload-limits
                spec:
                  limits:
                    - default:
                        cpu: 500m
                        memory: 512Mi
                      defaultRequest:
                        cpu: 100m
                        memory: 128Mi
                      type: Container
