apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-observability-ho
  namespace: ocm-policies-ho
placementRef:
  name: shared-placement-ho
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: policy-set-observability
    kind: PolicySet
    apiGroup: policy.open-cluster-management.io
