apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - clusterset-binding.yaml
  - placement.yaml
  - acm-placement-configmap.yaml
  - argocd-ocm-rbac.yaml
  - binding-security.yaml
  - binding-platform.yaml
  - binding-compliance.yaml
  - binding-capacity.yaml
  - binding-observability.yaml
  - binding-infrastructure.yaml
