apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-platform-namespace
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-platform-namespace
        spec:
          remediationAction: enforce
          severity: medium
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: platform-ops
                  labels:
                    managed-by: ocm
                    team: platform
