apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: policy-set-observability
spec:
  description: "Políticas de Observabilidade (Logs, Métricas)"
  policies:
    - policy-observability-namespace
