apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: policy-set-compliance
spec:
  description: "Conformidade NIST/CIS"
  policies:
    - policy-compliance-nist-baseline
