apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: policy-set-infrastructure
spec:
  description: "Gestão de Ciclo de Vida de Infra"
  policies:
    - policy-infra-storage-class
