apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-infra-storage-class
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-infra-storage-class
        spec:
          remediationAction: enforce
          severity: medium
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: storage.k8s.io/v1
                kind: StorageClass
                metadata:
                  annotations:
                    storageclass.kubernetes.io/is-default-class: "true"
                  name: standard
                provisioner: rancher.io/local-path
