apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: headlamp-bu-acme-pr.local
    target:
      kind: Ingress
      name: headlamp-ingress
