apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-platform-pr
  namespace: ocm-policies-pr
placementRef:
  name: shared-placement-pr
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: policy-set-platform
    kind: PolicySet
    apiGroup: policy.open-cluster-management.io
